name: swift_checker

on: [pull_request] # only PR will run

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  danger:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gems
        uses: actions/cache@v2
        env:
          cache-name: gems
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            v1-${{ runner.os }}-${{ env.cache-name }}-
      - name: Install Gems
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
        run: |
          bundle config set path 'vendor/bundle' ; bundle config set clean 'true'
          bundle check || bundle install
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger
